# description of this workflow, can be anything you want
name: Build pi json

# we need to let GitHub know _when_ we want to run this workflow, typically only when we create a new tag.
# this will target pushes to the master branch and pull request.
# this part can be heavily customized to your liking, like targeting only tags that match a certain word,
# other branches or even pullrequests.
on:
  push:
    branches: [ main ]
    paths:
      - 'data/sims/**'              # Any file inside the /data/sims folder
  workflow_dispatch:
  workflow_run:
    workflows: ["Gather PI Data"]
    types:
      - completed


# a workflow is built up as jobs, and within these jobs are steps
jobs:
  collect-and-commit:
    runs-on: ubuntu-latest
    env:
      OPENROUTER_API_KEY:     ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - uses: actions/checkout@v4    
      - run: pip install openai     
      
      - name: Merge into pi_values.json
        run: |
          python backend_scripts/gather_pi_data_matrix.py --merge-results
      
      - name: Generate description texts
        run: |
            python backend_scripts/generate_pi_description_text.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config pull.rebase true   # rebase
          git add data/
          git commit -m "Updated Pi Data" || echo "No changes to commit"
          git pull || echo "No changes to pull"
          git push || echo "No changes to push"