name: Update SharedMedia Assets

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
   - cron: '0 10 * * WED'

jobs:
  update-media:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - addon_id: "rkGryYKy"
            file_name: "SharedMedia_Causese/Soundpaths.lua"
            parent_key: "shared-media-causese"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pycryptodome

      - name: Run asset update script
        env:
          ADDON_ID: ${{ matrix.addon_id }}
          FILE_NAME: ${{ matrix.file_name }}
          PARENT_KEY: ${{ matrix.parent_key }}
          WAGO_ADDONS_DECRYPT_KEY: ${{ secrets.WAGO_ADDONS_DECRYPT_KEY }}
          WAGO_ADDONS_DECRYPT_IV:  ${{ secrets.WAGO_ADDONS_DECRYPT_IV }}
        run: |
          python backend_scripts/fetchWagoAddon.py

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/json/
          git diff --staged --quiet || git commit -m "ci: update Sharedmedia data for ${{ matrix.addon_id }}"
          git push
