name: Gather PI Data

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * WED'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    
    env:
      WCL_CLIENT_ID:     ${{ secrets.WCLOGS_CLIENT_ID }}
      WCL_CLIENT_SECRET: ${{ secrets.WCLOGS_CLIENT_SECRET }}
      GITHUB_TOKEN:      ${{ secrets.GITHUB_TOKEN }}
    
    outputs:
      matrix: ${{ steps.make-matrix.outputs.matrix }}
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python & dependencies
        uses: actions/setup-python@v4

      - run: pip install requests

      - name: Prepare sim-matrix JSON
        id: make-matrix
        run: |
            # this will write matrix.json + all your debug logs
            python backend_scripts/gather_pi_data_matrix.py --prepare

            # now load matrix.json into the GH Action output
            echo "matrix=$(jq -c . matrix.json)" >> $GITHUB_OUTPUT
      - name: Upload generated profiles
        uses: actions/upload-artifact@v4
        with:
            name: simc-profiles
            path: data/sims/profiles/

  simulate:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
      - name: Download generated profiles
        uses: actions/download-artifact@v4
        with:
            name: simc-profiles
            path: data/sims/profiles
      - uses: actions/setup-python@v4
        with: { python-version: '3.12' }
      - run: pip install requests
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libssl-dev libpcap-dev libcurl4-openssl-dev
    
      - name: Clone and build SimulationCraft CLI
        run: |
            git clone --depth=1 https://github.com/simulationcraft/simc.git simc
            mkdir simc/build && cd simc/build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_GUI=OFF
            make -j$(nproc)
            sudo cp simc /usr/local/bin/

      - name: Run one sim
        run: |
          python backend_scripts/gather_pi_data_matrix.py \
            --run-job \
            --sim-file="${{ matrix.sim_file }}" \
            --json-out="${{ matrix.json_out }}" \
            --html_out="${{ matrix.html_out }}" \
            --class="${{ matrix.class }}" \
            --spec="${{ matrix.spec }}" \
            --targets="${{ matrix.targets }}" \
            --pi="${{ matrix.pi }}" \
            --precision=0.05 \
            --iterations=50000 \

      - name: Upload json sim result
        uses: actions/upload-artifact@v4
        with:
          name: sim-json- ${{ matrix.class }}-${{ matrix.spec }}-t${{ matrix.targets }}-pi${{ matrix.pi }}
          path: ${{ matrix.json_out }}
      - name: Upload html sim result
        uses: actions/upload-artifact@v4
        with:
            name: sim-html- ${{ matrix.class }}-${{ matrix.spec }}-t${{ matrix.targets }}-pi${{ matrix.pi }}
            path: ${{ matrix.html_out }}    

  collect-and-commit:
    needs: simulate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download simc profiles
        uses: actions/download-artifact@v4       # pull in the .simc files you uploaded earlier :contentReference[oaicite:2]{index=2}
        with:
            name: simc-profiles
            path: data/sims/profiles
      - name: Download all sim JSONs
        uses: actions/download-artifact@v4
        with: { path: data/sims/final_sims }

      - name: Merge into pi_values.json
        run: |
          python backend_scripts/gather_pi_data_matrix.py --merge-results
      
      - name: Generate description texts
        run: |
            python backend_scripts/generate_pi_description_text.py
      - name: Auto-commit & push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated Pi Data"
          file_pattern: "data/**"
