name: Gather Journal info

on:
  schedule:
    - cron: '0 0 * * WED'
  workflow_dispatch:

jobs:
  gather-items:
    runs-on: ubuntu-latest
    env:
      BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
      BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pandas
        run: pip install pandas

      - name: Create data directory
        run: mkdir -p data

      - name: Download CSV
        run: curl -L "https://wago.tools/db2/JournalEncounter/csv?product=wow" -o data/JournalEncounter.csv

      - name: Convert CSV to JSON
        run: |
          python - <<EOF
          import pandas as pd
          df = pd.read_csv('data/JournalEncounter.csv')
          df.set_index('Name_lang', inplace=True)
          df.to_json('data/JournalEncounter.json', orient='index', indent=4)
          EOF
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config pull.rebase true   # rebase
          git add data/
          git commit -m "Updated JournalEncounter" || echo "No changes to commit"
          git pull || echo "No changes to pull"
          git push || echo "No changes to push"
