name: Gather PI Data

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * WED'

jobs:
  gather-pi:
    runs-on: ubuntu-latest
    env:
        WCL_CLIENT_ID: ${{ secrets.WCLOGS_CLIENT_ID }}
        WCL_CLIENT_SECRET: ${{ secrets.WCLOGS_CLIENT_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libssl-dev libpcap-dev libcurl4-openssl-dev

      - name: Clone and build SimulationCraft CLI
        run: |
            git clone --depth=1 https://github.com/simulationcraft/simc.git simc
            mkdir simc/build && cd simc/build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_GUI=OFF
            make -j$(nproc)
            sudo cp simc /usr/local/bin/
      - name: Run Gather PI Data Script
        env:
          WCL_CLIENT_ID: ${{ secrets.WCLOGS_CLIENT_ID }}
          WCL_CLIENT_SECRET: ${{ secrets.WCLOGS_CLIENT_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x backend_scripts/gather_pi_data.py
          python ./backend_scripts/gather_pi_data.py

      - name: Auto-commit & push updated data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated PiInfo"
          file_pattern: "data/**"
